### ISSUE TITLE
Forking to start an implementation!

### ISSUE THREAD

**Issue by navneethg** [grncdr/otssh#2]

**Comment by navneethg** [comment]
Use the Go implementation https://pkg.go.dev/golang.org/x/crypto/ssh#example-NewServerConn as base, and write lots of tests, that's the basic idea. Sounds good?

**Comment by neiser** [comment]
@navneethg Please see the conflict resolution protocol in https://github.com/grncdr/otssh/issues/1#issuecomment-766091649 

I hope you're ok with that!

**Comment by navneethg** [comment]
Go ahead, all good!

**Comment by grncdr** [comment]
Closing for now, I'll notify over in #1 if I get to you in the list @navneethg
