### ISSUE TITLE
Clarification: Number of connections per session

### ISSUE THREAD

**Issue by navneethg** [grncdr/otssh#3]
Can multiple clients connect to a **one-time** session?

Formally, this clarification touches upon the transititions among the following states (numbers as on README):
4. Opens the listening TCP socket.
6. Accepts a connection on that socket.
7. Authenticates the connection using the provided authorized keys.
8. If authentication fails, closes the connection and returns to step 6.

All is well if the answer is yes (only one client per session), otherwise we fork the state transitions at step 4 for each client, correct?

**Comment by grncdr** [comment]
The short answer is no.

The longer answer depends on how I interpret your question. The important requirement is that as soon as a connection is **authenticated** that's it, no more clients are allowed in. The listening socket **may** remain open, but it **should not** accept any more clients, and it definitely **must not** authenticate and start additional shell sessions.

Furthermore, once the single authenticated session ends, the entire `otssh` process **must** exit.
